# 워크플로우 -> 자동화 할 작업의 설계서 -> action.yml
#

name: first workflow
on: push # 이벤트 트리거
jobs: # jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: install nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: install dependencies
              uses: npm ci

            - name: run lint
              uses: npm run lint
    build: # job의 이름
        runs-on: ubuntu-latest
        steps: # step 정의
            - name: Checkout Code
              uses: actions/checkout@v4 # action -> 재사용가능한 작업

              # 노드 버전을 맞춰야 할 경우에 가상환경에 노드를 추가 설치
            - name: install nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: install deps
              run: npm ci # ci -> clean install -> package-lock.json

            - name: run build
              run: npm run build
