name: Basic CI

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: run ci

            - name: run test
              run: npm test

            - name: Build project
              run: npm build
